# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Szabi/Documents/Vivado/proiectUARTNexys4DDR/proiectUARTNexys4DDR.cache/wt [current_project]
set_property parent.project_path C:/Users/Szabi/Documents/Vivado/proiectUARTNexys4DDR/proiectUARTNexys4DDR.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Szabi/Documents/Vivado/proiectUARTNexys4DDR/proiectUARTNexys4DDR.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Szabi/Documents/Vivado/proiectUARTNexys4DDR/proiectUARTNexys4DDR.srcs/sources_1/imports/new/I2C_Master.vhd
  C:/Users/Szabi/Documents/Vivado/proiectUARTNexys4DDR/proiectUARTNexys4DDR.srcs/sources_1/imports/new/I2C_Controller.vhd
  C:/Users/Szabi/Documents/Vivado/proiectUARTNexys4DDR/proiectUARTNexys4DDR.srcs/sources_1/imports/new/debouncer.vhd
  C:/Users/Szabi/Documents/Vivado/proiectUARTNexys4DDR/proiectUARTNexys4DDR.srcs/sources_1/imports/new/baud_rate_generator.vhd
  C:/Users/Szabi/Documents/Vivado/proiectUARTNexys4DDR/proiectUARTNexys4DDR.srcs/sources_1/imports/Desktop/displ7seg.vhd
  C:/Users/Szabi/Documents/Vivado/proiectUARTNexys4DDR/proiectUARTNexys4DDR.srcs/sources_1/imports/new/TX_FSM.vhd
  C:/Users/Szabi/Documents/Vivado/proiectUARTNexys4DDR/proiectUARTNexys4DDR.srcs/sources_1/imports/new/rx_fsm.vhd
  C:/Users/Szabi/Documents/Vivado/proiectUARTNexys4DDR/proiectUARTNexys4DDR.srcs/sources_1/imports/new/main_unit.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Szabi/Documents/Vivado/proiectUARTNexys4DDR/proiectUARTNexys4DDR.srcs/constrs_1/imports/Desktop/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Szabi/Documents/Vivado/proiectUARTNexys4DDR/proiectUARTNexys4DDR.srcs/constrs_1/imports/Desktop/Nexys4DDR_Master.xdc]


synth_design -top main_unit -part xc7a100tcsg324-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


write_checkpoint -force -noxdef main_unit.dcp

catch { report_utilization -file main_unit_utilization_synth.rpt -pb main_unit_utilization_synth.pb }
